---
- hosts: all
  sudo: yes
  gather_facts: yes

  pre_tasks:
    - name: Package index is updated
      apt: update_cache=yes
           cache_valid_time=3600

    - name: Locale is set
      locale_gen: name=en_US.UTF-8
                  state=present

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian
    - geerlingguy.java
    - geerlingguy.elasticsearch
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - ANXS.postgresql

  tasks:
    - apt: name="{{ item }}"
           state=installed
      with_items: ancillary_packages

    - name: Hosts are present
      lineinfile: dest=/etc/hosts
                  line="127.0.0.1 {{ item }}"
      with_items:
        - es
        - postgres
        - rabbitmq
        - redis
        - zk

    - name: Pip is present
      shell: curl https://bootstrap.pypa.io/get-pip.py | python

    - name: Virtualenv is present
      pip: name=virtualenv
           extra_args='-I'

    - name: Motd is updated
      command: "echo 'Welcome! This is the lymph base box built on top of Ubuntu 14.04. Happy, developing :)' > /etc/motd"
