---
- hosts: all
  sudo: yes
  gather_facts: yes

  vars:
   - postgresql_version: 9.4
   - postgresql_ext_install_postgis: yes
   - postgresql_max_prepared_transactions: 10
   - postgresql_databases:
     - name: vagrant
   - postgresql_users:
     - name: vagrant
       pass: vagrant
       encrypted: no
   - postgresql_user_privileges:
     - name: vagrant
       priv: "ALL"
       role_attr_flags: "SUPERUSER"
   - postgresql_pg_hba_trust_hosts:
     - local
     - 127.0.0.1

  pre_tasks:
    - name: Package index is updated
      apt: update_cache=yes
           cache_valid_time=3600

    - name: Locales are set
      lineinfile: state=present
                  dest=/etc/default/locale
                  line="\"{{ item }}=en_US.UTF-8\""
      with_items:
        - LANG
        - LANGUAGE
        - LC_ALL
    
    - name: Locales are generated
      shell: "{{ item }}"
      with_items:
        - locale-gen en_US en_US.UTF-8
        - dpkg-reconfigure locales
      args:
        creates: /var/lib/locales/supported.d/local

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian
    - geerlingguy.java
    - geerlingguy.elasticsearch
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - ANXS.postgresql

  tasks:
    - apt: name="{{ item }}"
           state=installed
      with_items:
        # libs
        - gcc
        - build-essential
        - python-dev
        - python-virtualenv
        - python-setuptools
        - libpq-dev
        - libssl-dev
        - libffi-dev
        - libjpeg-dev
        # middleware
        - rabbitmq-server
        - redis-server
        - zookeeper
        - zookeeperd
        # tools
        - git
        - wget
        - curl
        - vim
        - tmux

    - name: Middleware is running
      service: name="{{ item }}"
               state=started
               enabled=yes
      with_items:
        - redis-server
        - zookeeper

    - name: Hosts are present
      lineinfile: dest=/etc/hosts
                  line="127.0.0.1 {{ item }}"
      with_items:
        - es
        - postgres
        - rabbitmq
        - redis
        - zk

    - name: Pip is present
      shell: curl https://bootstrap.pypa.io/get-pip.py | python

    - name: Virtualenv is present
      pip: name=virtualenv
           extra_args='-I'

    - name: Motd is updated
      command: "echo 'Welcome! This is the lymph base box built on top of Ubuntu 14.04. Happy, developing :)' > /etc/motd"
